name: ui_kit
description: "UI-Kit"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  cached_network_image: ^3.4.1
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
