name: {{name.snakeCase()}}
description: Neoflex {{name.snakeCase()}} template

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  local_auth: ^2.1.7
  reactive_forms: ^16.1.1
  retrofit: ^4.0.3
  super_banners: ^0.0.1  
  {{name.snakeCase()}}_core:
    path: ./packages/{{name.snakeCase()}}_core

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  process_run: ^0.13.2
  retrofit_generator: ^8.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
    - assets/icons/
    - .prod.env
    - .dev.env
