name: config
description: "Config related package for JNP."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
