targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/src/navigation/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          include:
            - lib/src/navigation/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/src/data/models/**/*.dart
        # options:
        #   field_rename: snake
      freezed:freezed:
        generate_for:
          include:
            - lib/src/presentation/blocs/**/**.dart
            - lib/src/presentation/cubits/**/**.dart
            - lib/src/data/models/**/*.dart
      