name: core
description: Core module package."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  auto_route: 9.3.0+1
  config:
    path: ../../shared/config
  connectivity_plus: ^6.1.3
  dependencies:
    path: ../../shared/dependencies
  device_info_plus: 11.2.2
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  dio_smart_retry: ^7.0.1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: 2.4.4
  hive: ^2.2.3
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.2
  talker: ^4.6.14
  talker_dio_logger: ^4.6.14
  talker_flutter: ^4.6.14

dev_dependencies:
  auto_route_generator: 9.3.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0
